apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: bobbycar-regional-policy
  namespace: policies
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-bobbycar-namespace
        spec:
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: bobbycar
    #- objectDefinition:
    #    apiVersion: policy.open-cluster-management.io/v1
    #    kind: ConfigurationPolicy
    #    metadata:
    #      name: bobby-car-operator-group
    #    spec:
    #      severity: low
    #      namespaceSelector:
    #        include: 
    #          - bobbycar
    #      object-templates:
    #        - complianceType: musthave
    #          objectDefinition:
    #            apiVersion: operators.coreos.com/v1alpha1
    #            kind: OperatorGroup
    #            metadata:
    #              name: bobbycar-og
    #            spec:
    #              targetNamespaces:
    #                - policies
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-amq-broker
        spec:
          severity: low
          namespaceSelector:
            include: 
              - bobbycar
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: amq-broker-rhel8
                  namespace: bobbycar
                spec:
                  channel: 7.10.x
                  name: amq-broker-rhel8
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-amq-streams
        spec:
          severity: low
          namespaceSelector:
            include: 
              - bobbycar
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: amq-streams
                  namespace: bobbycar
                spec:
                  channel: stable
                  name: amq-streams
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-camel-k
        spec:
          severity: low
          namespaceSelector:
            include: 
              - bobbycar
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: install-redhat-camel-k
                  namespace: bobbycar
                spec:
                  channel: latest
                  name: red-hat-camel-k
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-datagrid
        spec:
          severity: low
          namespaceSelector:
            include: 
              - policies
              - bobbycar
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: install-redhat-datagrid
                  namespace: bobbycar
                spec:
                  channel: 8.2.x
                  name: datagrid
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: install-serverless
        spec:
          severity: low
          namespaceSelector:
            include: 
              - openshift-operators
              - policies
              - openshift-serverless
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-serverless
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: serverless-operators
                  namespace: openshift-serverless
                spec: {}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: serverless-operator
                  namespace: openshift-serverless
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: serverless-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
    
    
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-bobbycar-regional
  namespace: policies
placementRef:
  name: bobbycar-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
- name: bobbycar-regional-policy
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: bobbycar-regional-placement
spec:
  clusterConditions: []
  clusterSelector:
    matchExpressions:
      - key: bobbycar
        operator: In
        values:
          - regional
